### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by tlynn** [rfk/threading2#4]
``` python
>>> import threading2
>>> threading2.current_thread().priority = 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "threading2/t2_base.py", line 378, in _set_priority
    self.priority = priority
...
  File "threading2/t2_base.py", line 378, in _set_priority
    self.priority = priority
  File "threading2/t2_base.py", line 378, in _set_priority
    self.priority = priority
  File "threading2/t2_base.py", line 378, in _set_priority
    self.priority = priority
  File "threading2/t2_base.py", line 377, in _set_priority
    if self.is_alive():
  File "/usr/lib/python2.6/threading.py", line 679, in isAlive
    return self.__started.is_set() and not self.__stopped
RuntimeError: maximum recursion depth exceeded
```

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
